apiVersion: v1
kind: Service
metadata:
  name: spring-boot-api-03-app
  namespace: default
  labels:
    app: spring-boot-api-03-app
spec:
  selector:
    app: spring-boot-api-03-app
  ports:
    - protocol: TCP
      port: 8080
      #nodePort: 30074
<<<<<<< HEAD
  type: NodePort
=======
  type: NodePort
>>>>>>> 510312b03be0e08eeb0ed281c1aedbf283711462
